language: php

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - mysql -e 'INSERT INTO `users` (`id`, `email`, `password`, `name`, `mobile`, `activated`, `created_at`, `updated_at`) VALUES (NULL, 'test@test.com', '$2y$10$DfQ5SIBgXVZS2EucVfIFZeRdLrNwtQIWuOJFgEH78jVWnyXB5D7Fe', 'edgar', '0400000000', '1', NULL, NULL);'

before_install:

script:
  - vendor/bin/phpunit
  
services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor
    
env:
  - TRAVIS_NODE_VERSION="4"